{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}

package:
  name: vcfwiper
  version: {{ data.get('version') }}

#app:
#  icon: icon_64x64.png
  
source:
  git_url: https://github.com/mazzalab/vcfwiper.git

build:
  number: 0
  entry_points:
    - vcfwiper = vcf_wiper.wiper:wipe_vcf
 
requirements:
  host:
    - python ==3.9
    - numpy x.x
    
  run:
    - python ==3.9
    - colorama ==0.4.4
    - click ==8.0.1

test:
  imports:
    - vcf_wiper
  commands:
    - vcfwiper --help
    
about:
  home: https://github.com/mazzalab/vcfwiper
  summary: A package to wipe out and fix uncompliant VCF files
  license: MIT
  license_file: LICENSE.txt
